version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      # docker-compose tomará los valores de tu archivo .env
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_DATABASE: '${DB_NAME}'
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build: .
    container_name: spring_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      # Aquí también usamos las variables del .env
      SPRING_DATASOURCE_URL: 'jdbc:mysql://db:3306/${DB_NAME}'
      SPRING_DATASOURCE_USERNAME: '${DB_USERNAME}'
      SPRING_DATASOURCE_PASSWORD: '${DB_PASSWORD}'
      SPRING_JPA_HIBERNA_DDL_AUTO: 'update'

      SPRING_MAIL_HOST: '${EMAIL_HOST}'
      SPRING_MAIL_PORT: '${EMAIL_PORT}'
      SPRING_MAIL_USERNAME: '${EMAIL_USERNAME}'
      SPRING_MAIL_PASSWORD: '${EMAIL_PASSWORD}'

      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: 'true'
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: 'true'

volumes:
  mysql-data:
